name: bibliotecaoop
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/ 
    - assets/icons/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets\fonts\Open_Sans\OpenSans-Light.ttf
          weight: 300
        - asset: assets\fonts\Open_Sans\OpenSans-Regular.ttf
          weight: 400
        - asset: assets\fonts\Open_Sans\OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Open_Sans\OpenSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets\fonts\Open_Sans\OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets\fonts\Open_Sans\OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets\fonts\Open_Sans\OpenSans-BoldItalic.ttf
          weight: 800
          style: italic
